name: CD - Deploy CRM Production

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: self-hosted
    steps:
      - name: Pull latest code and rebuild production
        run: |
          cd /home/jeanxxiii-crm/jeanxxiii-crm

          git pull origin main

          make prod-down

          docker compose -f docker-compose.prod.yml build --no-cache

          make prod-up

          docker image prune -f
